### ISSUE TITLE
Fail 11.3.1.1	If the algorithm value is id-RSASSA-PSS, verify that the signature->parameters field is populated with SHA-256 (OID = 2.16.840.1.101.3.4.2.1). For the other RSA algorithms, the parameters field is populated with NULL. For ECDSA, the parameters field is absent.

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#162]

**Comment by MKSCertiPath** [comment]
The test case  sp800_78_Test_3, which implements this appears to have some incorrect logic. For example it treats the two ECDSA cases ecdsaWithSHA256 and ecdsaWithSHA384 differently. The requirement says 
parameter field should be absent for all ECDSA cases but the test code applies it to only ecdsaWithSHA384 and allows parameter to be present for ecdsaWithSHA256.

Also it is not clear how we can test all the cases implemented in this test case. For a given smart card it will only test one of the various possible conditions. We will need to have four different cards (times two: one good and one bad; so total 8 cards are needed to test this) corresponding to the four separate cases in order to conclude that the test case is indeed fully implemented.

![image](https://user-images.githubusercontent.com/9324182/60293619-979f9580-98ed-11e9-8864-cef600669bdf.png)

**Comment by MKSCertiPath** [comment]
Another issue is that it is not really checking if signature->parameters field is populated with SHA-256 (OID = 2.16.840.1.101.3.4.2.1) for algorithm value of id-RSASSA-PSS. It is simply adding the algorithm to an ArrayList instead of checking if it exists in the certificate.
