### ISSUE TITLE
8.3.1 AND 8.7.1.1 - Container blob is no larger than 1905 bytes

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#194]

**Comment by bob-fontana** [comment]
My Carillon PIV-I has 3 certificates whose sizes exceed the 1905-byte limit.  We ought not to enforce this because SP800-85B draft(3) says:

_The values in this column denote the guaranteed minimum capacities, in bytes, of the on-card storage containers. Cards with larger containers may be produced and determined conformant._
